### ISSUE TITLE
Bug for parsing `override method` clauses when a default expression refers to a field

### ISSUE THREAD

**Issue by capfredf** [racket/rhombus#622]
```
#lang rhombus

interface something:
  method hello(a)
  
class Fruit(price):
  implements something
  override method
  | hello(a when a == price):
      #true
```

The parser can't parse the code above because of `price` in the default expression, spitting out an unhelpful error message.

```
?: bad syntax
  in: #false
  errortrace...:
  context...:
```

By contrast, the parser is happy when the method has no clauses, ie. `override method hello(a when a == price)`.
